# Project: Tutorial
# Makefile created by Dev-C++ 4.9.9.2

CPP  = g++.exe
CC   = gcc.exe
WINDRES = windres.exe
RES  = Tutorial_private.res
OBJ  = main.o $(RES)
LINKOBJ  = main.o $(RES)
LIBS =  -L"G:/PortableApps/Dev-CppPortable/App/devcpp/lib" -mwindows ../../PortableApps/Dev-CppPortable/App/devcpp/lib/libole32.a ../../PortableApps/Dev-CppPortable/App/devcpp/lib/libuuid.a ../../PortableApps/Dev-CppPortable/App/devcpp/lib/liboleaut32.a  -s 
INCS =  -I"G:/PortableApps/Dev-CppPortable/App/devcpp/include" 
CXXINCS =  -I"G:/PortableApps/Dev-CppPortable/App/devcpp/lib/gcc/mingw32/3.4.2/include"  -I"G:/PortableApps/Dev-CppPortable/App/devcpp/include/c++/3.4.2/backward"  -I"G:/PortableApps/Dev-CppPortable/App/devcpp/include/c++/3.4.2/mingw32"  -I"G:/PortableApps/Dev-CppPortable/App/devcpp/include/c++/3.4.2"  -I"G:/PortableApps/Dev-CppPortable/App/devcpp/include" 
BIN  = ../../PortableApps/LitestepPortable/App/Litestep/Tutorial/Tutorial.exe
CXXFLAGS = $(CXXINCS)  
CFLAGS = $(INCS)  
RM = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before ../../PortableApps/LitestepPortable/App/Litestep/Tutorial/Tutorial.exe all-after


clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o "..\..\PortableApps\LitestepPortable\App\Litestep\Tutorial\Tutorial.exe" $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

Tutorial_private.res: Tutorial_private.rc 
	$(WINDRES) -i Tutorial_private.rc --input-format=rc -o Tutorial_private.res -O coff 
